SELECT * FROM _METADATA.APP_LOG;

SELECT * FROM _METADATA.APP_TOKENS;

SELECT * FROM _METADATA.APP_TOKEN_REDEMPTIONS;

SELECT * FROM _METADATA.SNOWFLAKE_TARGET_DATABASES;

SELECT * FROM _METADATA.SNOWFLAKE_DATABASES_PROCESSED;
